# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2dfaf3b2361534bc3973b227b829d52d522f8018afc909f398b61a27bd2e95d3e2101a41da487f349d38a4b83ee6fae95af9d2ab44d71f16d362fc604deb9b

test:
  secret_key_base: fab6053f8d9f1544b14a969e47458e7a64b1b10405bd63986846b8239a82ff59dda82844c4445c81d00bb744d700e630ad6c9065ff9983f1fd463420caf4cfe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: "any"
  secret_key_base: "any"
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
